services:
  jekyll:
    image: jekyll/jekyll:latest
    command: tail -F /dev/null
    volumes:
      - ./jekyll:/srv/jekyll
  caddy:
    image: caddy:2.6.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/server/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - $PWD/server/root:/srv
      - $PWD/server/caddy/certs:/data/certs

volumes:
  caddy_data:
    external: true
    name: kippel.org_caddy_data
  caddy_config:
    external: true
    name: kippel.org_caddy_config
