name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, prod]
    steps:
      - uses: actions/checkout@v4
        name: Checkout sources
        with:
          path: /srv/www/blog.kippel.org
      - name: Compile site
        run: just compile
