name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, prod]
    steps:
      - uses: actions/checkout@v4
        name: Checkout sources
      - name: Copy to wwwroot
        run: |
          cp -r ${GITHUB_WORKSPACE}/* /srv/www/blog.kippel.org/
      - name: Compile site
        working-directory: /srv/www/blog.kippel.org/
        run: just compile
