name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, prod]
    steps:
      - uses: actions/checkout@v4
        name: Checkout sources
      - name: Compile site
        run: just compile
      - name: Copy to wwwroot
        run: |
          cp -r ./jekyll/_site/* /srv/www/blog.kippel.org/server/root/
