name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, prod]
    defaults:
      run:
        shell: bash
        working-directory: /srv/www/blog.kippel.org
    steps:
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Compile site
      run: |
        ls
        mv ${GITHUB_WORKSPACE}/* /srv/www/blog.kippel.org/
        just compile
